@echo off
REM ==========================================================================
REM  eye-clinic-setup.bat  -  ONE-FILE installer + updater for Eye Clinic.
REM
REM  Copy this single file anywhere on the clinic PC and double-click it.
REM    * First run  -> downloads Eye Clinic from GitHub, bundles a portable
REM      Node, builds it, seeds the database, and makes an "Eye Clinic" icon.
REM    * Run again  -> checks GitHub for a newer release and updates in place,
REM      never touching C:\ClinicData (patient data) or the saved settings.
REM
REM  It elevates itself (asks for Administrator) automatically.
REM ==========================================================================
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 >nul
title Eye Clinic Setup

REM --- self-elevate to Administrator (firewall rule + scheduled task need it) ---
net session >nul 2>&1
if errorlevel 1 (
  echo Requesting Administrator permission...
  powershell -NoProfile -Command "Start-Process -FilePath '%~f0' -Verb RunAs" >nul 2>&1
  exit /b
)

REM --- per-machine constants ---
set "REPO=FlowChazt/eye-emr"
set "NODE_VERSION=22.11.0"
set "BASE=C:\EyeClinic"
set "APP=%BASE%\app"
set "NODE=%BASE%\node"
set "DATA=C:\ClinicData"
set "BACKUPS=%DATA%\backups"
set "CONFIG=%DATA%\config.bat"
set "VERFILE=%DATA%\installed-version.txt"
set "NPM=%NODE%\npm.cmd"

echo ==========================================================
echo   Eye Clinic setup
echo   App folder : %APP%
echo   Data folder: %DATA%
echo ==========================================================
echo.

REM --- 1. find the latest published release on GitHub (public repo, no token) ---
echo Checking GitHub for the latest version...
set "LATEST="
for /f "usebackq delims=" %%i in (`powershell -NoProfile -Command "try { (Invoke-RestMethod -UseBasicParsing -Headers @{ 'User-Agent' = 'eye-clinic-setup' } 'https://api.github.com/repos/%REPO%/releases/latest').tag_name } catch { '' }"`) do set "LATEST=%%i"
if not defined LATEST (
  echo.
  echo   Could not reach GitHub, or no release has been published yet.
  echo   Check the internet connection and try again.
  echo.
  pause
  exit /b 1
)
echo   Latest release: %LATEST%

REM --- 2. decide install vs update vs already-current ---
set "INSTALLED="
if exist "%VERFILE%" set /p INSTALLED=<"%VERFILE%"
if not exist "%APP%\package.json" set "INSTALLED="
if /i "%INSTALLED%"=="%LATEST%" (
  echo.
  echo   Eye Clinic is already up to date ^(%LATEST%^). Nothing to do.
  echo.
  pause
  exit /b 0
)
if defined INSTALLED ( set "MODE=update" ) else ( set "MODE=install" )
echo   Mode: %MODE%
echo.

REM --- 3. data folders ---
if not exist "%DATA%"    mkdir "%DATA%"
if not exist "%BACKUPS%" mkdir "%BACKUPS%"
if not exist "%BASE%"    mkdir "%BASE%"

REM --- 4. portable Node (download once, reused across updates) ---
if not exist "%NODE%\node.exe" (
  echo Downloading portable Node %NODE_VERSION% ...
  powershell -NoProfile -Command "Invoke-WebRequest -UseBasicParsing 'https://nodejs.org/dist/v%NODE_VERSION%/node-v%NODE_VERSION%-win-x64.zip' -OutFile '%TEMP%\eye-node.zip'" || goto :fail
  if exist "%TEMP%\eye-node-extract" rmdir /S /Q "%TEMP%\eye-node-extract"
  powershell -NoProfile -Command "Expand-Archive -Force '%TEMP%\eye-node.zip' '%TEMP%\eye-node-extract'" || goto :fail
  move "%TEMP%\eye-node-extract\node-v%NODE_VERSION%-win-x64" "%NODE%" >nul || goto :fail
  del "%TEMP%\eye-node.zip" >nul 2>&1
  rmdir /S /Q "%TEMP%\eye-node-extract" >nul 2>&1
)
set "PATH=%NODE%;%PATH%"

REM --- 5. settings: load existing, or ask on first install ---
if exist "%CONFIG%" call "%CONFIG%"
if not exist "%CONFIG%" call :ask_options
if not defined PORT set "PORT=3000"
if not defined AUTOSTART set "AUTOSTART=Y"

REM --- 6. generate config once (keeps SESSION_SECRET stable across updates) ---
if not exist "%CONFIG%" (
  echo Generating one-time settings ^(SESSION_SECRET^)...
  for /f %%S in ('powershell -NoProfile -Command "[guid]::NewGuid().ToString('N')+[guid]::NewGuid().ToString('N')"') do set "SECRET=%%S"
  (
    echo REM Auto-generated by eye-clinic-setup.bat - do not edit by hand.
    echo set DB_PATH=%DATA%\clinic.db
    echo set PORT=%PORT%
    echo set HOSTNAME=0.0.0.0
    echo set AUTOSTART=%AUTOSTART%
    echo set SESSION_SECRET=!SECRET!
  ) > "%CONFIG%"
)

REM --- 7. fetch the release source and lay it down in %APP% ---
if /i "%MODE%"=="update" (
  echo Stopping the running server...
  taskkill /F /IM node.exe >nul 2>&1
  if exist "%APP%" rmdir /S /Q "%APP%"
)
if not exist "%APP%" mkdir "%APP%"

echo Downloading Eye Clinic %LATEST% ...
powershell -NoProfile -Command "Invoke-WebRequest -UseBasicParsing -Headers @{ 'User-Agent' = 'eye-clinic-setup' } 'https://api.github.com/repos/%REPO%/zipball/%LATEST%' -OutFile '%TEMP%\eye-src.zip'" || goto :fail
if exist "%TEMP%\eye-src" rmdir /S /Q "%TEMP%\eye-src"
powershell -NoProfile -Command "Expand-Archive -Force '%TEMP%\eye-src.zip' '%TEMP%\eye-src'" || goto :fail
set "EXDIR="
for /d %%d in ("%TEMP%\eye-src\*") do set "EXDIR=%%d"
if not defined EXDIR ( echo   Extracted source not found. & goto :fail )
robocopy "%EXDIR%" "%APP%" /E /NFL /NDL /NJH /NJS /NC /NS >nul
if errorlevel 8 goto :fail
del "%TEMP%\eye-src.zip" >nul 2>&1
rmdir /S /Q "%TEMP%\eye-src" >nul 2>&1

REM --- 8. install deps + build + standalone post-build copies ---
echo.
echo Installing dependencies ^(fetches the prebuilt better-sqlite3^)...
call "%NPM%" install --prefix "%APP%" || goto :fail
echo.
echo Building production bundle...
call "%NPM%" run build --prefix "%APP%" || goto :fail
echo.
echo Copying static assets into the standalone bundle...
xcopy /E /I /Y "%APP%\.next\static" "%APP%\.next\standalone\.next\static" >nul || goto :fail
if exist "%APP%\public" xcopy /E /I /Y "%APP%\public" "%APP%\.next\standalone\public" >nul
xcopy /E /I /Y "%APP%\drizzle" "%APP%\.next\standalone\drizzle" >nul
if not exist "%APP%\.next\standalone\node_modules\better-sqlite3\build" xcopy /E /I /Y "%APP%\node_modules\better-sqlite3" "%APP%\.next\standalone\node_modules\better-sqlite3" >nul

REM --- 9. seed the production DB ONCE (never clobber existing data) ---
echo.
if not exist "%DATA%\clinic.db" (
  echo Seeding a fresh database at %DATA%\clinic.db ...
  set "DB_PATH=%DATA%\clinic.db"
  call "%NPM%" run seed --prefix "%APP%" || goto :fail
  echo   default login: eye / eyeclinic  ^(CHANGE IT after first login^)
) else (
  echo Database already exists - leaving it untouched.
)

REM --- 10. shortcuts (desktop, start menu, and startup if autostart chosen) ---
echo.
echo Creating the "Eye Clinic" shortcut...
set "VBS=%APP%\deploy\windows\run-clinic.vbs"
set "ICON=%APP%\deploy\windows\eye-clinic.ico"
set "LNK=Eye Clinic.lnk"
powershell -NoProfile -Command "$w=New-Object -ComObject WScript.Shell; $t=@([Environment]::GetFolderPath('Desktop'),[Environment]::GetFolderPath('Programs')); if($env:AUTOSTART -eq 'Y'){ $t+=[Environment]::GetFolderPath('Startup') }; foreach($d in $t){ if($d -and (Test-Path $d)){ $s=$w.CreateShortcut((Join-Path $d $env:LNK)); $s.TargetPath=(Join-Path $env:SystemRoot 'System32\wscript.exe'); $s.Arguments='\"'+$env:VBS+'\"'; $s.WorkingDirectory=(Split-Path $env:VBS); $s.IconLocation=$env:ICON; $s.Description='Eye Clinic'; $s.Save(); Write-Host ('  shortcut: '+(Join-Path $d $env:LNK)) } }"

REM --- 11. firewall rule for LAN access + daily backup at 23:00 ---
echo.
echo Allowing LAN access on port %PORT% and registering the daily backup...
netsh advfirewall firewall delete rule name="Eye EMR" >nul 2>&1
netsh advfirewall firewall add rule name="Eye EMR" dir=in action=allow protocol=TCP localport=%PORT% >nul
schtasks /create /tn "Eye EMR Backup" /tr "powershell -NoProfile -ExecutionPolicy Bypass -File \"%APP%\deploy\windows\backup-clinic.ps1\"" /sc daily /st 23:00 /rl highest /f >nul

REM --- 12. record the installed version ---
>"%VERFILE%" echo %LATEST%

echo.
echo ==========================================================
if /i "%MODE%"=="install" (
  echo  INSTALLED Eye Clinic %LATEST%.
  echo  - Double-click the desktop icon "Eye Clinic" to start.
  echo  - First login: eye / eyeclinic  ^(change the password!^).
) else (
  echo  UPDATED Eye Clinic to %LATEST%.
  echo  - Your data and password are unchanged.
)
echo  - This PC:    http://localhost:%PORT%
echo  - Other PCs:  http://THIS-PC-IP:%PORT%   ^(run 'ipconfig' for the IP^)
echo ==========================================================
echo.
pause
exit /b 0

REM --------------------------------------------------------------------------
:ask_options
echo First-time setup - choose your options ^(press Enter for the default^):
:askport
set "PORT="
set /p "PORT=  Port to run Eye Clinic on [3000]: "
if not defined PORT set "PORT=3000"
echo %PORT%| findstr /r "^[0-9][0-9]*$" >nul || ( echo     Please enter a number. & goto askport )
if %PORT% LSS 1024  ( echo     Use a port between 1024 and 65535. & goto askport )
if %PORT% GTR 65535 ( echo     Use a port between 1024 and 65535. & goto askport )
set "AUTOSTART=Y"
set /p "AUTOSTART=  Start Eye Clinic automatically when the PC turns on? [Y/n]: "
if /i "%AUTOSTART%"=="n" ( set "AUTOSTART=N" ) else ( set "AUTOSTART=Y" )
echo.
goto :eof

:fail
echo.
echo *** Setup FAILED. See the error above. ***
echo     Your data in %DATA% was not touched.
echo.
pause
exit /b 1
