@echo off
REM ==========================================================================
REM install.bat  -  ONE-TIME Eye EMR setup on the clinic's Windows PC.
REM Run this ONCE, as Administrator (right-click -> Run as administrator).
REM Re-running is safe: it never overwrites C:\ClinicData (the patient data)
REM and keeps the SESSION_SECRET it generated the first time.
REM
REM To ship a code update later, use update.bat instead.
REM ==========================================================================
setlocal EnableDelayedExpansion
chcp 65001 >nul

REM --- must be admin (firewall rule + scheduled task need it) ---
net session >nul 2>&1
if errorlevel 1 (
  echo.
  echo   This must be run as Administrator.
  echo   Right-click install.bat -^> "Run as administrator".
  echo.
  pause
  exit /b 1
)

set "HERE=%~dp0"
pushd "%HERE%..\.." >nul
set "ROOT=%CD%"
popd >nul

set "DATA=C:\ClinicData"
set "DB=%DATA%\clinic.db"
set "BACKUPS=%DATA%\backups"
set "PORT=3000"
set "CONFIG=%HERE%config.bat"

echo ==========================================================
echo  Eye EMR install
echo  App folder : %ROOT%
echo  Data folder: %DATA%
echo  Port       : %PORT%
echo ==========================================================
echo.

REM --- 1. data folders ---
if not exist "%DATA%"    mkdir "%DATA%"
if not exist "%BACKUPS%" mkdir "%BACKUPS%"

REM --- 2. SESSION_SECRET: generate once, persist in config.bat ---
if not exist "%CONFIG%" (
  echo Generating one-time SESSION_SECRET...
  for /f %%S in ('powershell -NoProfile -Command "[guid]::NewGuid().ToString('N')+[guid]::NewGuid().ToString('N')"') do set "SECRET=%%S"
  (
    echo REM Auto-generated by install.bat - do not edit by hand.
    echo set DB_PATH=%DB%
    echo set PORT=%PORT%
    echo set HOSTNAME=0.0.0.0
    echo set SESSION_SECRET=!SECRET!
  ) > "%CONFIG%"
  echo   wrote %CONFIG%
) else (
  echo config.bat already exists - keeping existing SESSION_SECRET.
)

REM --- 3. install deps + build + post-build copies ---
echo.
echo Installing dependencies (this fetches the prebuilt better-sqlite3)...
call npm install --prefix "%ROOT%" || goto :fail

echo.
echo Building production bundle...
call npm run build --prefix "%ROOT%" || goto :fail

echo.
echo Copying static assets into the standalone bundle...
xcopy /E /I /Y "%ROOT%\.next\static" "%ROOT%\.next\standalone\.next\static" >nul || goto :fail
if exist "%ROOT%\public" xcopy /E /I /Y "%ROOT%\public" "%ROOT%\.next\standalone\public" >nul
REM safety net in case file-tracing missed them:
if not exist "%ROOT%\.next\standalone\drizzle" xcopy /E /I /Y "%ROOT%\drizzle" "%ROOT%\.next\standalone\drizzle" >nul
if not exist "%ROOT%\.next\standalone\node_modules\better-sqlite3\build" xcopy /E /I /Y "%ROOT%\node_modules\better-sqlite3" "%ROOT%\.next\standalone\node_modules\better-sqlite3" >nul

REM --- 4. seed the production DB ONCE (never clobber existing data) ---
echo.
if not exist "%DB%" (
  echo Seeding a fresh database at %DB% ...
  set "DB_PATH=%DB%"
  call npm run seed --prefix "%ROOT%" || goto :fail
  echo   default login: eye / eyeclinic  ^(CHANGE IT after first login^)
) else (
  echo Database already exists at %DB% - leaving it untouched.
)

REM --- 5. shortcuts (desktop, start menu, autostart) ---
echo.
echo Creating shortcuts...
set "VBS=%HERE%run-clinic.vbs"
set "ICON=%ROOT%\app\favicon.ico"
if not exist "%ICON%" set "ICON=%SystemRoot%\System32\imageres.dll,15"
set "LNKNAME=โปรแกรมคลินิก.lnk"
powershell -NoProfile -Command "$w=New-Object -ComObject WScript.Shell; foreach($d in @([Environment]::GetFolderPath('Desktop'),[Environment]::GetFolderPath('Programs'),[Environment]::GetFolderPath('Startup'))){ if($d -and (Test-Path $d)){ $s=$w.CreateShortcut((Join-Path $d $env:LNKNAME)); $s.TargetPath=(Join-Path $env:SystemRoot 'System32\wscript.exe'); $s.Arguments='\"'+$env:VBS+'\"'; $s.WorkingDirectory=$env:HERE; $s.IconLocation=$env:ICON; $s.Description='Eye EMR'; $s.Save(); Write-Host ('  shortcut: '+(Join-Path $d $env:LNKNAME)) } }"

REM --- 6. firewall: allow inbound TCP on the port for LAN access ---
echo.
echo Adding firewall rule for LAN access on port %PORT% ...
netsh advfirewall firewall delete rule name="Eye EMR" >nul 2>&1
netsh advfirewall firewall add rule name="Eye EMR" dir=in action=allow protocol=TCP localport=%PORT% >nul

REM --- 7. daily backup scheduled task at 23:00 ---
echo.
echo Registering daily backup task at 23:00 ...
schtasks /create /tn "Eye EMR Backup" /tr "powershell -NoProfile -ExecutionPolicy Bypass -File \"%HERE%backup-clinic.ps1\"" /sc daily /st 23:00 /rl highest /f >nul

echo.
echo ==========================================================
echo  DONE.
echo  - Double-click the desktop icon "โปรแกรมคลินิก" to start.
echo  - First login: eye / eyeclinic  (change the password!).
echo  - Other PCs on the LAN: http://THIS-PC-IP:%PORT%
echo    (run 'ipconfig' to find THIS-PC-IP)
echo ==========================================================
echo.
pause
exit /b 0

:fail
echo.
echo *** Install FAILED. See the error above. ***
pause
exit /b 1
